#
# Deploy the back end data API microservice in Kubernetes
#

# ------------------- Deployment ------------------- #

kind: Deployment
apiVersion: apps/v1
metadata:
  name: data-api
  labels:
    app: data-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-api
  template:
    metadata:
      labels:
        app: data-api
    spec:
      containers:
      - name: data-api-pods

        # !CHANGE THIS! To your real image reference for the data-api  
        image: bcdemo.azurecr.io/smilr/data-api:windows-1709

        ports:
        - containerPort: 4000

        env:     
        - name: MONGO_CONNSTR
          value: mongodb://10.0.80.219
          #value: mongodb://smilr-demo:HeP2pYim0aqACPzsG9DGpqzuKWqAXNJMsF2bTrp03g2ovuJqDG0zd9rgg4C1FOwjhvdxVMHqVOYnqbgu8rWGpA==@smilr-demo.documents.azure.com:10255/?ssl=true&replicaSet=globaldb #mongodb://mongodb-svc.default
            
      # Wipe & initialize the database with demo data, remove if unwanted
      #initContainers:
      #  - name: init-demodata
      #    image: bcdemo.azurecr.io/smilr/data-api
      #    command: ['sh', '-c', 'cd demoData && node demoData.js']
      #    env:
      #      - name: MONGO_CONNSTR
      #        value: mongodb://mongodb-svc.default
      #      - name: WIPE_DB
      #        value: "1"