title: "Smilr: Microservices Reference App"
remote_theme: benc-uk/theme-msdark
favicon: /microservices-demoapp/angular/src/assets/img/logo.png
plugins:
  - jemoji
buttons:
  - b0:
    text: Main Guide
    href: /
  - b1:
    text: Docker
    href: /docs/containers
  - b2:
    text: Kubernetes
    href: /kubernetes
  - b3:
    text: Azure Templates
    href: /azure/templates
