version: '3'

# This file is intended for local testing and development
# Not for use with Docker Swarm or for scaling to multiple containers per service

services:
  frontend:
    image: ${DOCKER_REG}smilr/frontend${DOCKER_TAG}
    build: 
      context: .
      dockerfile: node/frontend/Dockerfile
      args: 
        build_config: production
    ports: 
      - 3000:3000
    environment:
      - API_ENDPOINT=http://localhost:4000/api

  data-api:
    image: ${DOCKER_REG}smilr/data-api${DOCKER_TAG}
    build: 
      context: .
      dockerfile: node/data-api/Dockerfile
      args: 
        build_info: Built from Docker compose
    ports: 
      - 4000:4000
    depends_on:
      - smilrdb     
    environment:
      - MONGO_CONNSTR=mongodb://smilrdb
    networks: 
      - smilr-net
  
  smilrdb:
    image: mongo:3.4-jessie
    ports: 
      - 27017:27017
    volumes:
      - db-data:/data/db
      - db-config:/data/configdb
    networks: 
      - smilr-net
  
volumes:
  db-data:
  db-config:

networks:
  smilr-net:
