{{ if .Values.dataApi.mongoConnStr }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "smilr.fullname" . }}-secrets
type: Opaque
data:
  mongoConnStr: {{ if .Values.dataApi.mongoConnStr }}
{{ end }}