{{- $frontendFullName := (printf "%s-frontend" (include "smilr.fullname" .)) -}}
{{- $dataApifullName := (printf "%s-data-api" (include "smilr.fullname" .)) -}}
{{- $ingressName := (printf "%s-ingress" (include "smilr.fullname" .)) -}}
{{- $certName := (printf "%s-cert" (include "smilr.fullname" .)) -}}

{{ if .Values.ingress.domainSuffix }}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ $ingressName }}"
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    {{ if .Values.ingress.certIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certIssuer }}
    {{ end }}
spec:
  {{ if or .Values.ingress.certIssuer .Values.ingress.certName }}
  tls:
  - hosts:
    - "{{ .Release.Name }}-{{ .Values.ingress.domainSuffix }}"
    {{ if .Values.ingress.certName }}
    secretName: {{ .Values.ingress.certName }}
    {{ else }}
    secretName: "{{ $certName }}"
    {{ end }}
  {{ end }}
  rules:
  - host: "{{ .Release.Name }}-{{ .Values.ingress.domainSuffix }}"
    http:
      paths:
      - path: /api
        backend:
          serviceName: {{ $dataApifullName }}
          servicePort: 80
      - path: /
        backend:
          serviceName: {{ $frontendFullName }}
          servicePort: 80

{{ else }}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ $ingressName }}-api"
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: "/api"
spec:
  rules:
  - http:
      paths:
      - path: "/{{ .Release.Name }}/api"
        backend:
          serviceName: {{ $dataApifullName }}
          servicePort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ $ingressName }}-frontend"
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/add-base-url: "true"
spec:
  rules:
  - http:
      paths:
      - path: "/{{ .Release.Name }}"
        backend:
          serviceName: {{ $frontendFullName }}
          servicePort: 80    
{{ end }}
