#
# Deploy the web API + load balanced service endpoint and the Orleans silo(s)
# 
# Requires:
# - Secret 'orleans-secrets' with key 'storageConnectionString' set to valid value
#

# ------------------- API Deployment ------------------- #
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: api
  labels:
    app: api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-spec
  template:
    metadata:
      labels:
        app: api-spec
    spec:
      containers:
      - name: api-pods
        # !CHANGE THIS! To your real image reference for the orleans-api
        image: bcdemo.azurecr.io/smilr/orleans-api 
        ports:
        - containerPort: 80
        env:     
        - name: Orleans__ClusterId
          value: orleans-smilr
        - name: Orleans__ConnectionString
          valueFrom:
            secretKeyRef:
              name: orleans-secrets
              key: storageConnectionString

---

# ------------------- Silo Deployment ------------------- #
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: silo
  labels:
    app: silo-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: silo-spec
  template:
    metadata:
      labels:
        app: silo-spec
    spec:
      containers:
      - name: silo-pods
        # !CHANGE THIS! To your real image reference for the orleans-silo
        image: bcdemo.azurecr.io/smilr/orleans-silo 
        env:     
        - name: Orleans__ClusterId
          value: orleans-smilr
        - name: Orleans__ConnectionString
          valueFrom:
            secretKeyRef:
              name: orleans-secrets
              key: storageConnectionString

---

# ------------------- Loadbalancer for API ------------------- #
kind: Service
apiVersion: v1
metadata:
  name: api-endpoint
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: api-spec