version: '3'

services:
  api:
    image: ${DOCKER_REG}smilr-orleans/api
    ports:
      - "5000-5010:80"
    build:
      context: .
      dockerfile: API/Dockerfile
  silo:
    image: ${DOCKER_REG}smilr-orleans/silo
    build:
      context: .
      dockerfile: Silo/Dockerfile
