#
# Deploy the back end data API microservice in Kubernetes
#

# ------------------- Deployment ------------------- #
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: data-api
  labels:
    app: data-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-api
  template:
    metadata:
      labels:
        app: data-api
    spec:
      containers:
      - name: data-api-pod
        image: bcdemo.azurecr.io/microsvc/data-api # !CHANGE THIS!
        ports:
        - containerPort: 4000
        env:
        - name: COSMOS_KEY
          valueFrom:
            secretKeyRef:
              name: cosmos-secrets
              key: cosmosKeySecret        
        - name: COSMOS_ENDPOINT
          value: https://microsurvey-cosmos.documents.azure.com # !CHANGE THIS!

---

# ------------------- Loadbalancer ------------------- #
kind: Service
apiVersion: v1
metadata:
  name: data-api-svc
  annotations:
    external-dns.alpha.kubernetes.io/hostname: microsurvey-api.democloud.org.uk # !CHANGE THIS!
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
  selector:
    app: data-api