#
# Deploy the front end Angular server microservice in Kubernetes
#

# ------------------- Deployment ------------------- #

kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-pod
        # !CHANGE THIS! To your real image reference for the frontend 
        image: bcdemo.azurecr.io/microsvc/frontend 
        ports:
        - containerPort: 3000
        env:       
        - name: API_ENDPOINT
          # !CHANGE THIS! To your real API endpoint DNS name or IP address
          value: http://microsurvey-api.democloud.org.uk/api 

---
# ------------------- Loadbalancer ------------------- #

kind: Service
apiVersion: v1
metadata:
  name: frontend-svc
  annotations:
    # !CHANGE THIS! To your real DNS domain, if not using external DNS just leave & ignore
    external-dns.alpha.kubernetes.io/hostname: microsurvey.democloud.org.uk 
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: frontend