#
# Deploy the back end data API microservice in Kubernetes
#

# ------------------- Deployment ------------------- #
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: data-api
  labels:
    app: data-api-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: data-api-spec
  template:
    metadata:
      labels:
        app: data-api-spec
    spec:
      containers:
      - name: data-api-pods
        # !CHANGE THIS! To your real image reference for the data-api  
        image: bcdemo.azurecr.io/smilr/data-api 
        ports:
        - containerPort: 4000
        env:
        - name: COSMOS_KEY
          valueFrom:
            secretKeyRef:
              name: cosmos-secrets
              key: cosmosKeySecret        
        - name: COSMOS_ENDPOINT
          # !CHANGE THIS! To your running Azure Cosmos DB account
          value: https://smilr-demo.documents.azure.com 

---

# ------------------- Loadbalancer ------------------- #
kind: Service
apiVersion: v1
metadata:
  name: data-api-endpoint
  annotations:
    # !CHANGE THIS! To your real DNS domain, if not using external DNS just leave & ignore
    external-dns.alpha.kubernetes.io/hostname: smilr-api.democloud.org.uk 
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
  selector:
    app: data-api-spec