apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:v0.4.7
        args:
        - --source=service
        - --domain-filter=democloud.org.uk # !CHANGE THIS! To your DNS domain
        - --provider=azure
        - --azure-resource-group=demo.misc # !CHANGE THIS! To the resource group in Azure with your DNS Zone
        volumeMounts:
        - name: azure-config-file
          mountPath: /etc/kubernetes
          readOnly: true
      volumes:
      - name: azure-config-file
        secret:
          secretName: azure-config-file