#
# Deploy the front end Angular server microservice in Kubernetes
#

# ------------------- Deployment ------------------- #

kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-pod
        image: bcdemo.azurecr.io/microsvc/frontend # !CHANGE THIS!
        ports:
        - containerPort: 3000
        env:       
        - name: API_ENDPOINT
          value: http://microsurvey-api.democloud.org.uk/api # !CHANGE THIS!  

---
# ------------------- Loadbalancer ------------------- #

kind: Service
apiVersion: v1
metadata:
  name: frontend-svc
  annotations:
    external-dns.alpha.kubernetes.io/hostname: microsurvey.democloud.org.uk # !CHANGE THIS!
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: frontend