#
# Deploy the front end service in Kubernetes
#

# ------------------- Deployment ------------------- #

kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: frontend-deploy
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-pod
        image: bcdemo.azurecr.io/microsvc/frontend
        ports:
        - containerPort: 3000
        env:       
        - name: API_ENDPOINT
          value: http://40.114.10.71/api        

---
# ------------------- Loadbalancer ------------------- #

kind: Service
apiVersion: v1
metadata:
  name: frontend-svc
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: frontend