#
# Deploy the back end service in Kubernetes
#

# ------------------- Deployment ------------------- #
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: backend-deploy
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-pod
        image: bcdemo.azurecr.io/microsvc/data-api
        ports:
        - containerPort: 4000
        env:
        - name: COSMOS_KEY
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: cosmosKeySecret        
        - name: COSMOS_ENDPOINT
          value: https://microsurvey.documents.azure.com

---

# ------------------- Loadbalancer ------------------- #
kind: Service
apiVersion: v1
metadata:
  name: backend-svc
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
  selector:
    app: backend