#
# Azure Pipeline - Build definition
# Build both Smilr Node.js images and push to Azure Container Registry
# Ben C, 2018
#

trigger:
- master

#
# NOTE! This variable group must be pre-created and populated
# - Expected variables: acr-name, acr-password
#
variables:
  - group: shared-variables

stages:
#
# Build stage
#
- stage: build
  displayName: 'Build containers'
  condition: false
  jobs:
  - job: buildJob
    displayName: 'Docker build & push to ACR'
    pool:
      vmImage: Ubuntu-16.04
    steps:
    #
    # Data API build steps, tag as both latest and BuildNumber
    #
    - bash: |
        docker build . -f node/data-api/Dockerfile -t $(acr-name).azurecr.io/smilr/data-api:latest -t $(acr-name).azurecr.io/smilr/data-api:$(Build.BuildNumber)
      displayName: 'Build data API image'

    - bash: |
        docker login $(acr-name).azurecr.io -u $(acr-name) -p $(acr-password)
        docker push $(acr-name).azurecr.io/smilr/data-api
      displayName: 'Push data API image(s) to ACR'

    #
    # Frontend build steps, tag as both latest and BuildNumber
    #
    - bash: |
        docker build . -f node/frontend/Dockerfile -t smilr/frontend:latest -t smilr/frontend:$(Build.BuildNumber) -t $(acr-name).azurecr.io/smilr/frontend:latest -t $(acr-name).azurecr.io/smilr/frontend:$(Build.BuildNumber)
      displayName: 'Build frontend image'

    - bash: |
        docker login $(acr-name).azurecr.io -u $(acr-name) -p $(acr-password)
        docker push $(acr-name).azurecr.io/smilr/frontend
      displayName: 'Push frontend image(s) to ACR'

#
# Deploy stage 1 - test environment
#
- stage: deployToTest
  condition: true
  displayName: 'Deploy to test'
  jobs:
  - deployment: deployWithACI
    displayName: 'Deploy using ACI'
    environment: Test
    pool:
      vmImage: Ubuntu-16.04
    variables:
      env-name: 'test'   
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureResourceGroupDeployment@2
            displayName: 'Deploy ARM Template'
            inputs:
              azureSubscription: Azure (AIRS)
              resourceGroupName: temp.smilr.$(env-name)
              location: westeurope
              csmFile: azure/templates/aci-mongo/azuredeploy.json
              csmParametersFile: azure/templates/aci-mongo/azuredeploy.parameters.json
              overrideParameters: '-acrName $(acr-name) -acrPassword $(acr-password) -dnsPrefix smilr-$(Build.BuildId)-$(env-name) -dataApiImageTag smilr/data-api:latest -frontendImageTag smilr/frontend:latest -releaseInfo "Deployed via pipelines: $(Agent.JobName) $(Build.BuildNumber) $(Build.Reason)"'

#
# Deploy stage 12 - staging environment
#
- stage: deployToStaging
  displayName: 'Deploy to staging'
  jobs:
  - deployment: deployWithACI
    displayName: 'Deploy using ACI'
    environment: Staging
    pool:
      vmImage: Ubuntu-16.04
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello          