#
# Azure Pipelines
# - Deploy to Kubernetes (AKS) using Helm chart
# Ben C, 2019
#

trigger: none

# NOTE! This variable group must be pre-created and populated
# - Expected variables: acr-name, acr-password
variables:
  - group: shared-variables

stages:
#
# Deploy stage 1 - AKS test environment
#
- stage: deployToTest
  displayName: Deploy to AKS Test
  
  variables:
    dns-prefix: smilr.56539f01234e4e00981e.westeurope