#
# Azure Pipelines
# - Deploy to Kubernetes (AKS) using Helm chart
# Ben C, 2019
#

trigger: none

# NOTE! This variable group must be pre-created and populated
# - Expected variables: acr-name, acr-password
variables:
  - group: shared-variables
