#
# Azure Pipelines
# - Deploy to Kubernetes (AKS) using Helm chart
# Ben C, 2019
#

trigger: none

# NOTE! This variable group must be pre-created and populated
# - Expected variables: acr-name, acr-password
variables:
  - group: shared-variables

stages:
#
# Deploy stage 1 - AKS test environment
#
- stage: deployToTest
  displayName: Deploy to AKS Test
  
  variables:
    dns-prefix: 'smilr.56539f01234e4e00981e.westeurope'
    azureSub: 'Azure (AIRS)'
    aksCluster: 'aks2019'
    aksResGrp: 'Demo.Containers'

  jobs:
  - deployment: deployToTest
    environment: 'aks-test'
    pool:
      vmImage: Ubuntu-16.04    
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: HelmInstaller@0
            displayName: 'Install Helm Version'
            inputs:
              helmVersion: 2.11.0
          
          - task: HelmDeploy@0
            displayName: 'Helm Update Dependencies'
            inputs:
              azureSubscription: $(azureSub)
              azureResourceGroup: $(aksResGrp)
              kubernetesCluster: $(aksCluster)
              command: dependency
              arguments: 'update kubernetes/helm/smilr'