#
# Azure Pipelines
# - Deploy to Kubernetes (AKS) using Helm chart
# Ben C, 2019
#

trigger: none

# NOTE! This variable group must be pre-created and populated
# - Expected variables: acr-name, acr-password, azure-sub, aks-resgrp, aks-cluster
variables:
  - group: shared-variables
  - name: dns-suffix
    value: 'smilr.56539f01234e4e00981e.westeurope.aksapp.io'

stages:
#
# Deploy stage 1 - AKS test namespace
#
- stage: deployToTest
  displayName: AKS Test

  jobs:
  - template: templates/helm-install.yml
    parameters:
      envName: test

#
# Deploy stage 2 - AKS staging namespace
#
- stage: deployToStaging
  displayName: AKS Staging

  jobs:
  - template: templates/helm-install.yml
    parameters:
      envName: staging

#
# Deploy stage 23 - AKS production namespace
#
- stage: deployToProduction
  displayName: AKS Production

  jobs:
  - template: templates/helm-install.yml
    parameters:
      envName: production