#
# Azure Pipelines
# - Deploy to Azure Container Instances across multiple stages
# Ben C, 2019
#
name: $(Date:yyyy-MM-dd)$(Rev:.rr)
trigger: none

schedules:
- cron: "30 5 * * 1"
  displayName: Weekly build
  branches:
    include:
    - master  
  always: true

# NOTE! The 'shared-variables' variable group must be pre-created and populated
# - Expected variables: acr-connection
variables:
  - group: shared-variables
  - name: cleanup
    value: true
  - name: resGroupPrefix
    value: temp.dave

stages:
#
# Deploy stage - test environment
#
- stage: deployToTest
  displayName: Deploy to Test
  
  variables:
    dns-prefix: smilr-$(Build.BuildId)-test
    location: westeurope

  jobs:
  - template: templates/deploy-aci-arm.yml
    parameters:
      envName: ACI-Test
      location: $(location)
      imageTag: latest
      resGroupPrefix: $(resGroupPrefix)
      dnsPrefix: $(dns-prefix)

  - template: templates/run-postman-tests.yml
    parameters:
      dependsOn: deployWithACI
      apiHost: $(dns-prefix)-api.$(location).azurecontainer.io
      frontHost: $(dns-prefix)-frontend.$(location).azurecontainer.io

#
# Deploy stage - staging environment
#
- stage: deployToStaging
  displayName: Deploy to Staging

  variables:
    dns-prefix: smilr-$(Build.BuildId)-staging
    location: westeurope

  jobs:
  - template: templates/deploy-aci-arm.yml
    parameters:
      envName: ACI-Staging
      location: $(location)
      imageTag: latest
      resGroupPrefix: $(resGroupPrefix)
      dnsPrefix: $(dns-prefix)

  - template: templates/run-postman-tests.yml
    parameters:
      dependsOn: deployWithACI
      apiHost: $(dns-prefix)-api.$(location).azurecontainer.io
      frontHost: $(dns-prefix)-frontend.$(location).azurecontainer.io

#
# Deploy stage - prod environment
#
- stage: deployToProduction
  displayName: Deploy to Production
  
  variables:
    dns-prefix: smilr-$(Build.BuildId)-prod
    location: westeurope

  jobs:
  - template: templates/deploy-aci-arm.yml
    parameters:
      envName: ACI-Production
      location: $(location)  
      imageTag: latest
      resGroupPrefix: $(resGroupPrefix)
      dnsPrefix: $(dns-prefix)

  - template: templates/run-postman-tests.yml
    parameters:
      dependsOn: deployWithACI
      apiHost: $(dns-prefix)-api.$(location).azurecontainer.io
      frontHost: $(dns-prefix)-frontend.$(location).azurecontainer.io

#
# Cleanup stage - remove resources after run
#
- stage: cleanup
  displayName: Remove Resources
  condition: eq(variables['cleanup'], 'true')

  jobs:
  - job: clanupJob
    displayName: Remove Resources Job
    steps:
      - task: AzureCLI@1
        inputs:
          azureSubscription: $(azure-connection)
          inlineScript: |
            az group delete -g $(resGroupPrefix).ACI-Production --yes --no-wait
            az group delete -g $(resGroupPrefix).ACI-Staging --yes --no-wait
            az group delete -g $(resGroupPrefix).ACI-Test --yes --no-wait