#
# Azure Pipelines
# - Deploy to Kubernetes (AKS) using Helm chart
# Ben C, 2019
#

trigger: none

# NOTE! This variable group must be pre-created and populated
# - Expected variables: acr-name, acr-password, azure-sub, aks-resgrp, aks-cluster
variables:
  - group: shared-variables

stages:
#
# Deploy stage 1 - AKS test environment
#
- stage: deployToTest
  displayName: Deploy to AKS Test
  
  variables:
    dns-name: 'smilr.56539f01234e4e00981e.westeurope.aksapp.io'

  jobs:
  - deployment: deployToTest
    environment: AKS-Test

    pool:
      vmImage: Ubuntu-16.04

    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: HelmInstaller@1
            displayName: 'Install Helm version'
            inputs:
              helmVersionToInstall: 2.12.3
          
          - task: HelmDeploy@0
            displayName: 'Helm update dependencies'
            inputs:
              azureSubscriptionEndpoint: $(azure-sub)
              azureResourceGroup: $(aks-resgrp)
              kubernetesCluster: $(aks-cluster)
              command: dependency
              arguments: 'update kubernetes/helm/smilr'

          - task: HelmDeploy@0
            displayName: 'Helm install to test namespace'
            inputs:
              azureSubscriptionEndpoint: $(azure-sub)
              azureResourceGroup: $(aks-resgrp)
              kubernetesCluster: $(aks-cluster)
              namespace: test
              command: upgrade
              chartType: FilePath
              chartPath: 'kubernetes/helm/smilr'
              releaseName: 'rel$(Build.BuildId)'
              overrideValues: 'registryPrefix=$(acr-name).azurecr.io/,domainSuffix=$(dns-name),dataApi.imageTag=latest,frontend.imageTag=latest,mongo.usePersistence=false'              