#
# Azure Pipelines
# - Pull both Smilr Node.js images from ACR
# - Retag as stable and push to ACR and Dockerhub
# Ben C, 2019
#

# No CI or automated runs
name: $(Date:yyyy-MM-dd)$(Rev:.rr)
trigger: none 

# NOTE! This variable group must be pre-created and populated
# - Expected variables: acr-name, acr-password, dockerhub-user, dockerhub-password
variables:
  - group: shared-variables

stages:
- stage: docker
  displayName: Update Stable Dockerhub
  jobs:
  - job: dockerJob
    displayName: Docker Job

    pool:
      vmImage: Ubuntu-16.04

    steps:

    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: $(acr-connection)

    - bash: |
        registry=$(cat $DOCKER_CONFIG/config.json | jq -r '.auths | with_entries( select(.key|contains("azurecr.io")) ) | keys[0]')
        secret=$(cat $DOCKER_CONFIG/config.json | jq -r '.auths | with_entries( select(.key|contains("azurecr.io")) ) [].auth' | python -m base64 -d)
        user=$(echo $secret | awk -F':' '{print $1}')
        password=$(echo $secret | awk -F':' '{print $2}')

        echo "##vso[task.setvariable variable=DOCKER_REG]$registry"
        echo "##vso[task.setvariable variable=DOCKER_USER]$user"
        echo "##vso[task.setvariable variable=DOCKER_PASSWORD]$password"
      displayName: Extract Docker registry details

    - task: Docker@2
      displayName: Pull data-api from ACR
      inputs:
        command: pull
        arguments: $(DOCKER_REG)/smilr/data-api:latest

    - task: Docker@2
      displayName: Pull frontend from ACR
      inputs:
        command: pull
        arguments: $(DOCKER_REG)/smilr/frontend:latest

    # Update tags
    - bash: |
        docker tag $(DOCKER_REG)/smilr/frontend:latest $(DOCKER_REG)/smilr/frontend:stable
        docker tag $(DOCKER_REG)/smilr/data-api:latest $(DOCKER_REG)/smilr/data-api:stable
        docker tag $(DOCKER_REG)/smilr/frontend:latest smilr/frontend:latest
        docker tag $(DOCKER_REG)/smilr/data-api:latest smilr/data-api:latest
        docker tag $(DOCKER_REG)/smilr/frontend:latest smilr/frontend:stable
        docker tag $(DOCKER_REG)/smilr/data-api:latest smilr/data-api:stable
      displayName: Tag images

    - task: Docker@2
      displayName: Push data-api stable image to ACR
      inputs:
        command: push
        containerRegistry: $(acr-connection)
        repository: smilr/data-api
        tags: stable

    - task: Docker@2
      displayName: Push frontend stable image to ACR
      inputs:
        command: push
        containerRegistry: $(acr-connection)
        repository: smilr/frontend
        tags: stable        

    - task: Docker@2
      displayName: Push data-api stable/latest images to Dockerhub
      inputs:
        command: push
        containerRegistry: $(dockerhub-connection)
        repository: smilr/data-api
        tags: |
          stable
          latest    

    - task: Docker@2
      displayName: Push frontend stable/latest images to Dockerhub
      inputs:
        command: push
        containerRegistry: $(dockerhub-connection)
        repository: smilr/frontend
        tags: |
          stable
          latest

    # # Push to ACR
    # - bash: |
    #     docker push $(acr-name).azurecr.io/smilr/frontend:stable
    #     docker push $(acr-name).azurecr.io/smilr/data-api:stable      
    #   displayName: 'Push stable images to ACR'

    # # Push to public Dockerhub
    # - bash: |
    #     docker login -u $(dockerhub-user) -p $(dockerhub-password)
    #     docker push smilr/frontend:stable
    #     docker push smilr/data-api:stable
    #     docker push smilr/frontend:latest
    #     docker push smilr/data-api:latest        
    #   displayName: 'Push stable/latest images to Dockerhub'