#
# Azure Pipelines
# - Pull both Smilr Node.js images from ACR
# - Retag as stable and push to ACR and Dockerhub
# Ben C, 2019
#

# No CI or automated runs
name: $(Date:yyyy-MM-dd)$(Rev:.rr)
trigger: none 

# NOTE! This variable group must be pre-created and populated
# - Expected variables: acr-name, acr-password, dockerhub-user, dockerhub-password
variables:
  - group: shared-variables
  - name: acr-name
    value: bcdemo

stages:
- stage: docker
  displayName: 'Update Stable Dockerhub'
  jobs:
  - job: dockerJob
    displayName: 'Docker Job'

    pool:
      vmImage: Ubuntu-16.04

    steps:

    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: $(acr-connection)

    - bash: |
        export ACR_NAME=$(cat $DOCKER_CONFIG/config.json | jq -r '.auths | with_entries( select(.key|contains("azurecr.io")) ) | keys[0]')
        secret=$(cat $DOCKER_CONFIG/config.json | jq -r '.auths | with_entries( select(.key|contains("azurecr.io")) ) [].auth' | python -m base64 -d)
        export ACR_USER=$(echo $secret | awk -F':' '{print $1}')
        export ACR_PASSWORD=$(echo $secret | awk -F':' '{print $2}')

        echo "##vso[task.setvariable variable=ACR_NAME]$ACR_NAME"
        echo "##vso[task.setvariable variable=ACR_USER]$ACR_USER"
        echo "##vso[task.setvariable variable=ACR_PASSWORD]$ACR_PASSWORD"

    - bash: printenv

    # - task: Docker@2
    #   displayName: Login to Docker Hub
    #   inputs:
    #     command: login
    #     containerRegistry: $(dockerhub-connection)

    # # Pull latest from ACR
    # - bash: |
    #     docker login $(acr-name).azurecr.io -u $(acr-name) -p $(acr-password)
    #     docker pull $(acr-name).azurecr.io/smilr/data-api:latest
    #     docker pull $(acr-name).azurecr.io/smilr/frontend:latest
    #   displayName: 'Pull latest images'

    - task: Docker@2
      displayName: Pull from ACR
      inputs:
        command: pull
        arguments: $(ACR_NAME)/smilr/data-api:latest

    # # Update tags
    # - bash: |
    #     docker tag $(acr-name).azurecr.io/smilr/frontend:latest $(acr-name).azurecr.io/smilr/frontend:stable
    #     docker tag $(acr-name).azurecr.io/smilr/data-api:latest $(acr-name).azurecr.io/smilr/data-api:stable
    #     docker tag $(acr-name).azurecr.io/smilr/frontend:latest smilr/frontend:latest
    #     docker tag $(acr-name).azurecr.io/smilr/data-api:latest smilr/data-api:latest
    #     docker tag $(acr-name).azurecr.io/smilr/frontend:latest smilr/frontend:stable
    #     docker tag $(acr-name).azurecr.io/smilr/data-api:latest smilr/data-api:stable
    #   displayName: 'Tag images'

    # # Push to ACR
    # - bash: |
    #     docker push $(acr-name).azurecr.io/smilr/frontend:stable
    #     docker push $(acr-name).azurecr.io/smilr/data-api:stable      
    #   displayName: 'Push stable images to ACR'

    # # Push to public Dockerhub
    # - bash: |
    #     docker login -u $(dockerhub-user) -p $(dockerhub-password)
    #     docker push smilr/frontend:stable
    #     docker push smilr/data-api:stable
    #     docker push smilr/frontend:latest
    #     docker push smilr/data-api:latest        
    #   displayName: 'Push stable/latest images to Dockerhub'