#
# Azure Pipeline - Build defintion
# Test the API, using ACI to run MongoDB and newman to run Postman tests
# Ben C, 2018
#

resources:
  - repo: self

trigger: none 

queue:
  name: Hosted Ubuntu 1604

variables:
  azure-sub: Azure (AIRS)  
  azure-resgroup: temp.smilr.mongo 
  azure-region: westeurope 
  mongo-image: mongo:3.4-jessie

steps:
#
# Stand up MongoDB in Container Instance
#
- task: AzureCLI@1
  inputs:
    azureSubscription: '$(azure-sub)'
    scriptLocation: inlineScript
    inlineScript: |
      az group create -n $(azure-resgroup) -l westeurope
      az container create -n mongodb-aci -g $(azure-resgroup) --image $(mongo-image) --port 27017 --ip-address public --dns-name-label mongodb-smilr-$(Build.BuildId)
  displayName: 'Create temp MongoDB with ACI'

#
# NPM install for data API modules
#
- bash: |
    cd node/data-api
    npm install 
  displayName: 'NPM install data API'

#
# Install Newman as global tool, in specific path
#
- bash: |
    npm install -g newman --prefix $(System.DefaultWorkingDirectory) 
  displayName: 'NPM install newman'
  
#
# Point data API at Mongo, and start as a background job
# Then run the Postman tests against the API using Newman
#
- bash: |
    export MONGO_CONNSTR=mongodb://mongodb-smilr-$(Build.BuildId).$(azure-region).azurecontainer.io:27017
    cd node/data-api
    npm start &
    sleep 2
    $(System.DefaultWorkingDirectory)/bin/newman run ../../etc/postman/Smilr.postman_collection.json -r junit -n 5 --timeout 8000 --folder API --global-var smilr-api-host="localhost:4000"
  displayName: 'Start data API & run tests with newman'
  continueOnError: true

#
# Publish test results 
#
- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'newman/*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/node/data-api'
  displayName: 'Publish Test Results'
  condition: always()
  
#
# Nuke the MongoDB instance
#
- task: AzureCLI@1
  inputs:
    azureSubscription: '$(azure-sub)'
    scriptLocation: inlineScript
    inlineScript: |
      az group delete -n $(azure-resgroup) --no-wait --yes
  displayName: 'Clean up resources'
  condition: always()