parameters:
  envName: ''
  imageTag: 'latest'
  resGroupPrefix: 'temp.smilr'
  dnsPrefix: ''
  location: 'westeurope'

jobs:
- deployment: deployWithACI
  displayName: 'Deploy using ACI'
  environment: ${{ parameters.envName }}

  pool:
    vmImage: Ubuntu-16.04

  variables:
    resGroup: ${{ parameters.resGroupPrefix }}.$(Environment.Name)

  strategy:
    runOnce:
      deploy:
        steps:
        # Checkout git source
        - checkout: self

        - template: acr-connection.yml

        # Deploy an ARM template from the repo and inject parameters
        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy ARM Template'
          inputs:
            azureSubscription: $(azure-connection)
            resourceGroupName: $(resGroup)
            location: ${{ parameters.location }}
            csmFile: azure/templates/aci-mongo/azuredeploy.json
            csmParametersFile: azure/templates/aci-mongo/azuredeploy.parameters.json
            overrideParameters: '-acrName $(ACR_NAME) -acrUser $(ACR_USER) -acrPassword $(ACR_PASSWORD) -dnsPrefix ${{ parameters.dnsPrefix }} -dataApiImageTag ${{ parameters.imageTag }} -frontendImageTag ${{ parameters.imageTag }} -releaseInfo "Deployed via pipelines: $(Agent.JobName) $(Build.BuildNumber) $(Build.Reason)"'

        # SANITY CHECK. Can be removed
        - task: AzureCLI@1
          inputs:
            azureSubscription: $(azure-connection)
            scriptLocation: inlineScript
            inlineScript: |
              az account show -o table
              az group list -o table
              az container list -o table
