parameters:
  envName: ''

jobs:
- deployment: deployWithACI
  displayName: 'Deploy using ACI'
  environment: ${{ parameters.envName }}

  pool:
    vmImage: Ubuntu-16.04

  variables:
    #env-name: ${{ parameters.envName }}
    location: westeurope
    #res-group: temp.smilr.$Environment.Name

  strategy:
    runOnce:
      deploy:
        steps:
        # Checkout git source
        - checkout: self

        - template: acr-connection.yml

        # Deploy an ARM template from the repo and inject parameters
        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy ARM Template'
          inputs:
            azureSubscription: $(azure-connection)
            resourceGroupName: temp.smilr.$(Environment.Name)
            location: $(location)
            csmFile: azure/templates/aci-mongo/azuredeploy.json
            csmParametersFile: azure/templates/aci-mongo/azuredeploy.parameters.json
            overrideParameters: '-acrName $(ACR_NAME) -acrUser $(ACR_USER) -acrPassword $(ACR_PASSWORD) -dnsPrefix $(dns-prefix) -dataApiImageTag latest -frontendImageTag latest -releaseInfo "Deployed via pipelines: $(Agent.JobName) $(Build.BuildNumber) $(Build.Reason)"'