parameters:
  envName: ''

jobs:
- deployment: deployWithACI
  displayName: 'Deploy using ACI'
  environment: ${{ parameters.envName }}

  pool:
    vmImage: Ubuntu-16.04

  variables:
    env-name: ${{ parameters.envName }}
    location: westeurope
    res-group: temp.smilr.${{ parameters.envName }}

  strategy:
    runOnce:
      deploy:
        steps:
        # Checkout git source
        - checkout: self

        - template: docker-reg-details.yml

        # Deploy an ARM template from the repo and inject parameters
        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy ARM Template'
          inputs:
            azureSubscription: $(azure-connection)
            resourceGroupName: $(res-group)
            location: $(location)
            csmFile: azure/templates/aci-mongo/azuredeploy.json
            csmParametersFile: azure/templates/aci-mongo/azuredeploy.parameters.json
            overrideParameters: '-acrName $(DOCKER_USER) -acrPassword $(DOCKER_PASSWORD) -dnsPrefix $(dns-prefix) -dataApiImageTag latest -frontendImageTag latest -releaseInfo "Deployed via pipelines: $(Agent.JobName) $(Build.BuildNumber) $(Build.Reason)"'