parameters:
  frontHost: ''
  apiHost: ''
  dependsOn: ''

jobs:
  - job: runTestsJob
    dependsOn: ${{ parameters.dependsOn }}
    displayName: 'Functional API tests'

    condition: and(succeeded(), ne(variables['skip-tests'], 'true'))

    pool:
      vmImage: Ubuntu-16.04

    steps:
    - checkout: self
    - bash: sleep 30
    - bash: npm install -g newman --prefix $(System.DefaultWorkingDirectory)
    - bash: $(System.DefaultWorkingDirectory)/bin/newman run etc/postman/Smilr.postman_collection.json -r junit -n 3 --global-var smilr-api-host="${{ parameters.apiHost }}" --global-var smilr-front-host="${{ parameters.frontHost }}" --timeout 180000
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'newman/*.xml'
      condition: succeededOrFailed()
