parameters:
  frontHost: ''
  apiHost: ''
  dependsOn: ''

jobs:
  - job: runTestsJob
    dependsOn: ${{ parameters.dependsOn }}
    displayName: 'Functional API tests'

    condition: and(succeeded(), ne(variables['skip-tests'], 'true'))

    pool:
      vmImage: Ubuntu-16.04

    steps:
    - checkout: self
    
    # Wait until URL is ready or 60 seconds
    - bash: ./etc/bash/urlWait.sh http://{{ parameters.apiHost }}/ 60
    
    # Install Newman CLI tool
    - bash: npm install -g newman --prefix $(System.DefaultWorkingDirectory)
    
    # Run the tests with Newman
    - bash: $(System.DefaultWorkingDirectory)/bin/newman run etc/postman/Smilr.postman_collection.json /
        --reporters junit --iteration-count 3 --timeout 180000 /
        --global-var smilr-api-host="${{ parameters.apiHost }}" /
        --global-var smilr-front-host="${{ parameters.frontHost }}"
    
    # Publish test results
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'newman/*.xml'
      condition: succeededOrFailed()
