name: Deploy to AKS

on:
  issue_comment:
    types: [created, deleted]
    
jobs:
  # ==================================================================================
  # Continuous deployment job - deploy to AKS
  # ==================================================================================
  release-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:  
    - name: 'Checkout repo'
      uses: actions/checkout@v1

    - name: 'Connect to AKS'
      uses: azure/aks-set-context@v1
      with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}' # Azure credentials
          resource-group: 'demo.aks'
          cluster-name: 'bcdemo'
      id: login

    - name: 'List kube'
      run: |
        ls -R .kube

    - name: 'Helm'
      run: |
        helm ls     