name: Deploy to AKS

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/aks-deploy.yml'
    
jobs:
  # ==================================================================================
  # Continuous deployment job - deploy to AKS
  # ==================================================================================
  release-job:
    env:
      ACR_NAME: bcdemo
      AKS_NAME: bcdemo
      RES_GRP: demo.aks
      IMAGE_TAG: latest
      DOMAIN: kube.benco.io
      CERT: kube-benco-io-cert

    runs-on: ubuntu-latest
    steps:  
    - name: 'Checkout repo'
      uses: actions/checkout@v1

    - name: 'Connect to AKS'
      uses: azure/aks-set-context@v1
      with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}' # Azure credentials
          resource-group: '${{ env.RES_GRP }}'
          cluster-name: '${{ env.AKS_NAME }}'
      id: login

    - name: 'Helm dep update'
      run: |
        helm dep update smilrkubernetes/helm/smilr

    - name: 'Helm install'
      run: |
        helm upgrade test-123 kubernetes/helm/smilr --install --namespace test --set "registryPrefix=$ACR_NAME.azurecr.io/,dataApi.imageTag=$IMAGE_TAG,frontend.imageTag=$IMAGE_TAG,ingress.domainSuffix=$DOMAIN,ingress.certName=$CERT"
