name: Deploy to AKS

on:
  issue_comment:
    types: [created, deleted]
    
jobs:
  # ==================================================================================
  # Continuous deployment job - deploy to AKS
  # ==================================================================================
  release-job:
    env:
      ACR_NAME: bcdemo
      AKS_NAME: bcdemo
      RES_GRP: demo.aks

    runs-on: ubuntu-latest
    steps:  
    - name: 'Checkout repo'
      uses: actions/checkout@v1

    - name: 'Connect to AKS'
      uses: azure/aks-set-context@v1
      with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}' # Azure credentials
          resource-group: $RES_GRP
          cluster-name: $AKS_NAME
      id: login

    - name: 'Helm'
      run: |
        helm upgrade test-123 kubernetes/helm/smilr --install --namespace test --set "registryPrefix=bcdemo.azurecr.io/,dataApi.imageTag=latest,frontend.imageTag=latest,ingress.domainSuffix=kube.benco.io,ingress.certName=kube-benco-io-cert"
