name: Build Node Images & Push to ACR
#on: [push]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: azure/container-actions/docker-login@master
      with:
        login-server: bcdemo.azurecr.io
        username: bcdemo
        password: ${{ secrets.ACR_PASSWORD }}
    
    - run: |
        docker build . -f node/data-api/Dockerfile -t bcdemo.azurecr.io/smilr/data-api:${{ github.sha }}
        docker push bcdemo.azurecr.io/smilr/data-api:${{ github.sha }}

    - run: |
        docker build . -f node/frontend/Dockerfile -t bcdemo.azurecr.io/smilr/frontend:${{ github.sha }}
        docker push bcdemo.azurecr.io/smilr/frontend:${{ github.sha }}